[project]
name = "mcp-server"
version = "0.1.0"
description = "MCP server for student assignment analysis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.1",
    "pandas"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
